### ISSUE TITLE
Urlmapping does not produce correct url parameters

### ISSUE THREAD

**Issue by asmbit** [groovyzk/grailszk#13] opened 2022-09-27 09:44 UTC
Starting from the [example application](https://github.com/maiconandsilva/grailszk-example) and adding 

```
class UrlMappings {

	static mappings = {
		...
		"/test/$path**?"(controller:'test')
	}
}
```

```
class TestController {

    def index() { render params }
}
```
produces wrong output if opening "http://localhost:8085/test/p1/p2/p3/p4?q1=1&q2=2":

**['q1':'1', 'q2':'2', 'controller':'test']**

The correct output should be:

**['q1':'1', 'q2':'2', 'path':'p1/p2/p3/p4', 'controller':'test']**

I tested also with the latest release 3.2.2.

Thanks, 
Andreas

**Comment by maiconandsilva** [comment] 2022-10-01 14:55
I couldn't reproduce it using version 3.2.2. See the [updated project](https://github.com/maiconandsilva/grailszk-example) with  TestController example.

TestController returns `['q1':'1', 'q2':'2', 'path':'p1/p2/p3/p4', 'controller':'test']` as the expected result.

@asmbit, can you confirm it's working?

**Comment by asmbit** [comment] 2022-10-15 09:31
Sorry, @maiconandsilva, i tested with your updated project. Same result:

![grafik](https://user-images.githubusercontent.com/44233176/195979293-df616806-63d7-4890-b00a-65c06849a31a.png)

**Comment by maiconandsilva** [comment] 2022-10-15 11:47
@asmbit, have you used the right example? The following URL should be used: **http://localhost:8085/test/p1/p2/p3/p4?q1=1&q2=2** to get the following result: **`['q1':'1', 'q2':'2', 'path':'p1/p2/p3/p4', 'controller':'test']`**

![image](https://user-images.githubusercontent.com/64911189/195984519-cbb76201-5256-4f10-9817-2ffcb150fa9f.png)

I'm going to close this issue as I cannot reproduce it.

**Closed by maiconandsilva** 2022-10-15 11:47 UTC
Labels: invalid

**Comment by asmbit** [comment] 2022-10-15 12:30
@maiconandsilva, you are right. With 3.2.2 no problem. 

No idea why it didn't work before. Sorry. 

Have a nice day, Andreas
